name: Release charts
on:
  # Manual trigger
  workflow_dispatch: { }
  push:
    branches:
      - master

env:
    HELM_VERSION: v3.13.1

jobs:
  release:
    name: Release charts
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      id-token: write # needed for keyless signing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to pull repo with all history
      
      # Lint values schemas
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall rust-script -y --github-token ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: rust-script tools/update_values_schemas.rs
      - run: git diff && git diff-index --quiet HEAD

      - name: Configure Git
        run: |
          set -ue
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true